### ISSUE TITLE
Support Jetton

### ISSUE THREAD

**Issue by lavanphat** [Gusarich/airdrop#1]
I read through the ReadMe, but I only see airdrops sent in TON. 

Does this project support sending airdrops using Jettton (a token I created myself)?

**Comment by Gusarich** [comment]
this project is literally meant for distributing jettons.

**Comment by izzm** [comment]
Is it possible to distribute TON with this smart contract?

**Comment by Gusarich** [comment]
> Is it possible to distribute TON with this smart contract?

you can rewrite the sending part to do anything
