### ISSUE TITLE
Timeout error when trying to send `claimAirdrop`

### ISSUE THREAD

**Issue by danielbui12** [Gusarich/airdrop#3]
I created a airdrop smart contract with 1 AirdropEntry which is also the deployer wallet.
Then I tried to execute `claimAirdrop` and always got timeout from TON API.

<img width="1255" alt="Screen Shot 2024-06-24 at 19 17 05" src="https://github.com/Gusarich/airdrop/assets/79790753/145f9649-677e-4220-b5f7-d5ac90c3b1d7">

Are there any problems in code? or problems are from TON API?

**Comment by danielbui12** [comment]
As far as I checked, there must be at lease 3 entities

**Comment by daviddanielisa22-byte** [comment]
UQAKrSxjZNIUWACJPcrec9_8zNHAqVb1DtV8CJ93kEUD04Qg
